### ISSUE TITLE
Créer un sommaire des exercices

### ISSUE THREAD

**Issue by Arnaud-D** [arobase-che/defis-zestuels#6]
En l'état, il est difficile d'explorer la banque d'exercices pour trouver son bonheur. Un genre de sommaire serait d'une grande aide.

Cette [liste faite par informaticienzero](https://zestedesavoir.com/forums/sujet/11397/depot-dexercices/?page=2#p190631) peut-être un bon point de départ.

**Comment by informaticienzero** [comment]
Je pense que chaque personne qui commitera un exercice devra l'ajouter à la liste sur le README, pour plus de facilité.

**Comment by arobase-che** [comment]
C'est bon la vous pensez ?

**Comment by yoch** [comment]
Je pense qu'il voulait plutot dire un truc comme ca: https://github.com/yoch/defis-zestuels/tree/index

**Comment by yoch** [comment]
J'ai ajouté des liens aux exercices existant sur le README (#15), il faudra essayer de le maintenir au fur et a mesure des ajouts / changements.
